name: autofix.ci
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - run: cargo fmt

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '24'

      - name: Update mermaid.js if nessesary
        id: mermaid_check
        run: |
          HASH_BEFORE=$(sha256sum payload/mermaid.js 2>/dev/null || echo "none")
          npm ci
          HASH_AFTER=$(sha256sum payload/mermaid.js 2>/dev/null || echo "none")
          if [ "$HASH_BEFORE" != "$HASH_AFTER" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: install integration test depedencencys
        if: steps.mermaid_check.outputs.changed == 'true'
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser

            cargo install cargo-binstall
            cargo binstall -y mdbook
            cargo binstall -y cargo-insta
      - name: Update integration test snapshots
        if: steps.mermaid_check.outputs.changed == 'true'
        run: cargo insta test --accept --test integration || true

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
